import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../_styles/globals.css";
import "../_styles/globals.media.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";
import Navbar from "../_components/Navbar/Navbar_";
import Footer from "../_components/Footer";
import ToasterComponent from "../_components/ToasterComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: `(prefers-color-scheme: dark)`,
        url: `/logo-dark.svg`,
        href: `/logo-dark.svg`,
      },
      {
        media: `(prefers-color-scheme: light)`,
        url: `/logo-light.svg`,
        href: `/logo-light.svg`,
      },
    ]
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider>
          <Navbar />
          <main>
            {children}

            <ToasterComponent />
            
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
